# Generated by Django 5.2.6 on 2025-10-02 01:42
"""Initial migration for sticky notes application."""

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    """Initial migration for creating StickyNote model."""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StickyNote',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                (
                    'created_at',
                    models.DateTimeField(default=django.utils.timezone.now)
                ),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sticky_notes_stickynote',
                'ordering': ['-updated_at'],
            },
        ),
    ]
